import { motion } from 'framer-motion'
import { SEOHead } from '../components/seo/SEOHead'

const fadeIn = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5, ease: 'easeOut' as const },
}

export function TermsOfService() {
  return (
    <>
      <SEOHead
        title="Terms of Service"
        description="Codex Terms of Service — the terms governing the use of our AI-powered code explanation tool."
        path="/terms"
      />
      <div className="max-w-4xl mx-auto px-6 py-16">
        <motion.div {...fadeIn}>
          <h1 className="text-4xl md:text-5xl font-bold mb-6 bg-gradient-to-r from-indigo-400 to-cyan-400 bg-clip-text text-transparent">
            Terms of Service
          </h1>
          <p className="text-slate-400 text-sm mb-12">Last updated: July 2026</p>
        </motion.div>

        <motion.div {...fadeIn} transition={{ duration: 0.5, ease: 'easeOut', delay: 0.1 }} className="space-y-6 text-slate-300 leading-relaxed text-sm">
          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-3">1. Acceptance of Terms</h2>
            <p>
              By using Codex, you agree to these Terms of Service. If you do not agree, please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-3">2. Service Description</h2>
            <p>
              Codex is an AI-powered code explanation tool that analyzes code snippets and provides structured explanations. The service is provided "as is" without any warranty, express or implied.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-3">3. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Submit malicious code or content intended to harm the service or its users</li>
              <li>Attempt to bypass rate limits or security measures</li>
              <li>Use the service for any illegal purpose or in violation of applicable laws</li>
              <li>Reverse engineer, decompile, or attempt to extract the source code of the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-3">4. Rate Limiting</h2>
            <p>
              To ensure fair access for all users, Codex enforces rate limits per device. Exceeding these limits will temporarily restrict access. Rate limits are subject to change at our discretion.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-3">5. Intellectual Property</h2>
            <p>
              The code explanations generated by Codex are provided for educational and reference purposes. You retain all rights to the code you submit. The Codex service, including its branding, design, and underlying technology, is the intellectual property of the Codex team.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-3">6. Limitation of Liability</h2>
            <p>
              Codex is provided free of charge. To the maximum extent permitted by law, we shall not be liable for any damages arising from your use of the service, including but not limited to direct, indirect, incidental, or consequential damages.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-3">7. Modifications</h2>
            <p>
              We reserve the right to modify or discontinue the service at any time without notice. We also reserve the right to update these terms. Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-3">8. Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with applicable laws. Any disputes arising from these terms shall be resolved in the competent courts of the jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-200 mb-3">9. Contact</h2>
            <p>
              For questions about these terms, please reach out through our contact page.
            </p>
          </section>
        </motion.div>
      </div>
    </>
  )
}